language: node_js
node_js:
- '12'
install:
- npm install
- npm run build
after_install:
- ls -l
- cd ..
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  target_branch: gh-pages
  local_dir: docs
  on:
    branch: master
